Repository RAF-SI-2022/Banka-1-Frontend, pull requests merged in 2023-03, with the labels that each got.

#10 UserService dodat
  src/app/services/user.service.spec.ts
  src/app/services/user.service.ts
Labels: needs-ok-to-test, size/S

#13 dodat endpoint i definisan headers
  src/app/services/user.service.ts
  src/environments/environment.ts
Labels: needs-ok-to-test, size/S

#14 Uradjen page za aktiviranje sifre i page za resetovanje sifre zajedno sa api req
  src/app/app.module.ts
  src/app/components/users/activate-password/activate-password.component.css
  src/app/components/users/activate-password/activate-password.component.html
  src/app/components/users/activate-password/activate-password.component.ts
  src/app/components/users/reset-password/reset-password.component.css
  src/app/components/users/reset-password/reset-password.component.html
  src/app/components/users/reset-password/reset-password.component.ts
  src/app/services/user.service.ts
Labels: size/L

#15 Završena stranica za registraciju korisnika
  src/app/components/users/add-user/add-user.component.css
  src/app/components/users/add-user/add-user.component.html
  src/app/components/users/add-user/add-user.component.ts
  src/app/model/user-model.ts
  src/app/model/user-position-enum.ts
  src/app/services/user.service.ts
Labels: size/L

#17 Završena stranica za izmenu korisnika
  src/app/components/users/update-user/update-user.component.css
  src/app/components/users/update-user/update-user.component.html
  src/app/components/users/update-user/update-user.component.ts
  src/app/model/user-model.ts
  src/app/services/user.service.ts
Labels: size/L

#11 Feature1
  src/app/components/users/list-users/list-users.component.css
  src/app/components/users/list-users/list-users.component.html
  src/app/components/users/list-users/list-users.component.ts
  src/app/model/UserModel.ts
  src/app/services/user.service.ts
  src/environments/environment.ts
Labels: size/L, needs-ok-to-test

#18 Login and reset password request pages
  package-lock.json
  src/app/components/users/login/login.component.css
  src/app/components/users/login/login.component.html
  src/app/components/users/login/login.component.ts
  src/app/components/users/reset-password-request/reset-password-request.component.css
  src/app/components/users/reset-password-request/reset-password-request.component.html
  src/app/components/users/reset-password-request/reset-password-request.component.ts
  src/app/model/jwt-payload.ts
  src/app/model/log-in-request.ts
  src/app/model/log-in-response.ts
  src/app/services/user.service.ts
Labels: size/L

#22 Paginacija, on close, refaktorisanje
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/components/app/app.component.html
  src/app/components/app/app.component.ts
  src/app/components/home/home.component.html
  src/app/components/home/home.component.ts
  src/app/components/users/activate-password/activate-password.component.html
  src/app/components/users/add-user/add-user.component.html
  src/app/components/users/list-users/list-users.component.css
  src/app/components/users/list-users/list-users.component.html
  src/app/components/users/list-users/list-users.component.ts
  src/app/components/users/login/login.component.html
  src/app/components/users/login/login.component.ts
  src/app/components/users/reset-password-request/reset-password-request.component.html
  src/app/components/users/reset-password-request/reset-password-request.component.ts
  src/app/components/users/reset-password/reset-password.component.html
  src/app/components/users/update-user/update-user.component.html
  src/app/model/jwt-payload.ts
  src/app/services/current-user.service.ts
  src/app/services/user.service.ts
  tsconfig.json
Labels: size/L

#21 Task 1
  src/app/components/users/my-profile/my-profile.component.css
  src/app/components/users/my-profile/my-profile.component.html
  src/app/components/users/my-profile/my-profile.component.ts
  src/app/services/user.service.ts
Labels: size/L

#25 definisani enumi, ispravljanje gresaka, dodat regex
  src/app/components/home/home.component.ts
  src/app/components/users/activate-password/activate-password.component.ts
  src/app/components/users/reset-password/reset-password.component.ts
  src/app/components/users/update-user/update-user.component.html
  src/app/components/users/update-user/update-user.component.ts
  src/app/model/user-position-enum.ts
  src/app/model/user-role-enum.ts
  src/app/services/current-user.service.ts
  src/app/services/user.service.ts
Labels: size/M

#26 Ispravljanje bagova i refaktorisanje
  src/app/app-routing.module.ts
  src/app/components/app/app.component.html
  src/app/components/app/app.component.ts
  src/app/components/users/activate-password/activate-password.component.ts
  src/app/components/users/add-user/add-user.component.html
  src/app/components/users/add-user/add-user.component.ts
  src/app/components/users/list-users/list-users.component.html
  src/app/components/users/list-users/list-users.component.ts
  src/app/components/users/login/login.component.ts
  src/app/components/users/my-profile/my-profile.component.css
  src/app/components/users/my-profile/my-profile.component.html
  src/app/components/users/my-profile/my-profile.component.ts
  src/app/components/users/reset-password-request/reset-password-request.component.ts
  src/app/components/users/reset-password/reset-password.component.ts
  src/app/components/users/update-user/update-user.component.html
  src/app/components/users/update-user/update-user.component.ts
  src/app/guards/login.guard.ts
  src/app/model/user/jwt-payload.ts
  src/app/model/user/log-in-request.ts
  src/app/model/user/log-in-response.ts
  src/app/model/user/user-model.ts
  src/app/model/user/user-position-enum.ts
  src/app/model/user/user-role-enum.ts
  src/app/services/user/current-user.service.spec.ts
  src/app/services/user/current-user.service.ts
  src/app/services/user/user.service.spec.ts
  src/app/services/user/user.service.ts
Labels: size/XL

#28 Cypress testovi za stranice
  cypress.config.ts
  cypress.env.json
  cypress/e2e/login.cy.ts
  cypress/support/e2e.ts
  cypress/tsconfig.json
  package-lock.json
  package.json
  tsconfig.json
Labels: size/XXL

#30 cypress testovi za moj profil i korisnike
  cypress/e2e/my-profile.cy.ts
  cypress/e2e/users.cy.ts
  cypress/support/commands.ts
  cypress/support/e2e.ts
  src/app/components/app/app.component.html
  src/app/components/users/my-profile/my-profile.component.css
  src/app/components/users/my-profile/my-profile.component.html
Labels: size/L

#31 Dodato testiranje stranice za dodavanje korisnika
  cypress.env.json
  cypress/e2e/add-user.cy.ts
  cypress/e2e/users.cy.ts
  cypress/support/commands.ts
  src/app/components/users/add-user/add-user.component.html
  src/app/components/users/list-users/list-users.component.html
Labels: size/L

#41 jos jedna opcija za toggle
  src/app/components/home/home.component.html
  src/styles.css
Labels: size/M

#42 Feature2
  src/app/components/capital/capital-checking/capital-checking.component.css
  src/app/components/capital/capital-checking/capital-checking.component.html
  src/app/components/capital/capital-checking/capital-checking.component.ts
  src/app/components/capital/capital-main/capital-main.component.html
  src/app/components/capital/capital-main/capital-main.component.ts
  src/app/components/capital/capital-margin/capital-margin.component.css
  src/app/components/capital/capital-margin/capital-margin.component.html
  src/app/components/capital/capital-margin/capital-margin.component.ts
  src/app/model/capital-checking.ts
  src/styles.css
Labels: size/L

#43 Uradjen page za trade s validaciom
  src/app/components/trades/trades-forex/trades-forex.component.css
  src/app/components/trades/trades-forex/trades-forex.component.html
  src/app/components/trades/trades-forex/trades-forex.component.ts
  src/app/components/trades/trades-main/trades-main.component.css
  src/app/components/trades/trades-main/trades-main.component.html
  src/app/components/trades/trades-main/trades-main.component.ts
  src/app/components/trades/trades/trades.component.css
  src/app/components/trades/trades/trades.component.html
  src/app/components/trades/trades/trades.component.ts
  src/app/model/stocks-enum.ts
Labels: size/L

#44 issue #37 completed
  src/app/components/stock-market/forex/forex.component.css
  src/app/components/stock-market/forex/forex.component.html
  src/app/components/stock-market/futures/futures.component.css
  src/app/components/stock-market/futures/futures.component.html
  src/app/components/stock-market/stock-main/stock-main.component.css
  src/app/components/stock-market/stock-main/stock-main.component.html
  src/app/components/stock-market/stock-main/stock-main.component.ts
  src/app/components/stock-market/stocks/stocks.component.css
  src/app/components/stock-market/stocks/stocks.component.html
  src/app/components/stock-market/stocks/stocks.component.ts
Labels: size/L

#45 Popup prozori
  src/app/components/capital/capital-margin/capital-margin.component.css
  src/app/components/capital/capital-margin/capital-margin.component.html
  src/app/components/capital/capital-margin/capital-margin.component.ts
  src/app/components/capital/checking-popup/checking-popup.component.css
  src/app/components/capital/checking-popup/checking-popup.component.html
  src/app/components/capital/checking-popup/checking-popup.component.ts
  src/app/components/capital/margin-popup/margin-popup.component.css
  src/app/components/capital/margin-popup/margin-popup.component.html
  src/app/components/capital/margin-popup/margin-popup.component.ts
  src/app/components/users/login/login.component.html
  src/app/components/users/my-profile/my-profile.component.html
  src/app/components/users/reset-password-request/reset-password-request.component.html
Labels: size/L

#57 Popup add contract i popup create company
  src/app/components/companies/create-company-popup/create-company-popup.component.css
  src/app/components/companies/create-company-popup/create-company-popup.component.html
  src/app/components/companies/create-company-popup/create-company-popup.component.ts
  src/app/components/contracts/add-contract-popup/add-contract-popup.component.css
  src/app/components/contracts/add-contract-popup/add-contract-popup.component.html
  src/app/components/contracts/add-contract-popup/add-contract-popup.component.ts
Labels: size/L

#58 "Odradjen izgled komponenti: kompanije, ugovori i porudbine"
  src/app/components/companies/companies/companies.component.css
  src/app/components/companies/companies/companies.component.html
  src/app/components/companies/companies/companies.component.ts
  src/app/components/contracts/contracts/contracts.component.css
  src/app/components/contracts/contracts/contracts.component.html
  src/app/components/contracts/contracts/contracts.component.ts
  src/app/components/orders/orders.component.css
  src/app/components/orders/orders.component.html
  src/app/components/orders/orders.component.ts
  src/app/model/companies-contract-model.ts
Labels: size/L

#60 Checking and margin transactions pop-up
  src/app/components/capital/checking-transactions-popup/checking-transactions-popup.component.css
  src/app/components/capital/checking-transactions-popup/checking-transactions-popup.component.html
  src/app/components/capital/checking-transactions-popup/checking-transactions-popup.component.ts
  src/app/components/capital/margin-transactions-popup/margin-transactions-popup.component.css
  src/app/components/capital/margin-transactions-popup/margin-transactions-popup.component.html
  src/app/components/capital/margin-transactions-popup/margin-transactions-popup.component.ts
  src/app/components/stock-market/forex/forex.component.css
  src/app/components/stock-market/forex/forex.component.html
  src/app/components/stock-market/forex/forex.component.ts
  src/app/components/stock-market/futures/futures.component.css
  src/app/components/stock-market/stocks/stocks.component.css
Labels: size/L
