Repository RAF-SI-2022/Banka-1-Frontend, pull requests merged in 2023-05, with the labels that each got.

#110 cene akcija
  src/app/components/capital/capital-checking/capital-checking.component.html
  src/app/components/capital/capital-checking/capital-checking.component.ts
  src/app/components/trades/trades-forex/trades-forex.component.html
  src/app/components/trades/trades/trades.component.html
  src/app/model/user/user-model.ts
Labels: size/S

#116 "Stranica za zaposlene."
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/components/app/app.component.html
  src/app/components/employees/employees-dialog/employees-dialog.component.css
  src/app/components/employees/employees-dialog/employees-dialog.component.html
  src/app/components/employees/employees-dialog/employees-dialog.component.spec.ts
  src/app/components/employees/employees-dialog/employees-dialog.component.ts
  src/app/components/employees/employees-list/employees.component.css
  src/app/components/employees/employees-list/employees.component.html
  src/app/components/employees/employees-list/employees.component.spec.ts
  src/app/components/employees/employees-list/employees.component.ts
  src/app/model/employee/employee.ts
  src/app/services/employee/employees.service.spec.ts
  src/app/services/employee/employees.service.ts
Labels: size/XL

#117 Odradjen servis, funkcionalnost i izgled za kompanije.
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/components/companies/companies/companies.component.html
  src/app/components/companies/companies/companies.component.ts
  src/app/components/companies/company-details/company-details.component.html
  src/app/components/companies/company-details/company-details.component.ts
  src/app/components/companies/create-company-popup/create-company-popup.component.html
  src/app/components/companies/create-company-popup/create-company-popup.component.ts
  src/environments/environment.ts
Labels: size/L
