Repository RAF-SI-2022/Banka-1-Frontend, pull requests merged in 2023-04, with the labels that each got.

#63 akcije, forex + detaljni prikazi
  .browserslistrc
  package-lock.json
  package.json
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/components/stock-market/forex-detail/forex-detail.component.css
  src/app/components/stock-market/forex-detail/forex-detail.component.html
  src/app/components/stock-market/forex-detail/forex-detail.component.ts
  src/app/components/stock-market/forex/forex.component.css
  src/app/components/stock-market/forex/forex.component.html
  src/app/components/stock-market/forex/forex.component.ts
  src/app/components/stock-market/stock-detail/stock-detail.component.css
  src/app/components/stock-market/stock-detail/stock-detail.component.html
  src/app/components/stock-market/stock-detail/stock-detail.component.ts
  src/app/components/stock-market/stocks/stocks.component.html
  src/app/components/stock-market/stocks/stocks.component.ts
  src/app/model/stocks/forex-time-series.ts
  src/app/model/stocks/forex.ts
  src/app/model/stocks/stock-time-series.ts
  src/app/model/stocks/time-series-query-enum.ts
  src/app/services/stocks/forex.service.spec.ts
  src/app/services/stocks/forex.service.ts
  src/app/services/stocks/stocks.service.ts
  src/environments/environment.ts
  src/styles.css
  src/test.ts
  tsconfig.json
Labels: size/XXL

#64 zavrsena trgovina
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/components/app/app.component.html
  src/app/components/home/home.component.ts
  src/app/components/orders/orders-admin/orders-admin.component.css
  src/app/components/orders/orders-admin/orders-admin.component.html
  src/app/components/orders/orders-admin/orders-admin.component.spec.ts
  src/app/components/orders/orders-admin/orders-admin.component.ts
  src/app/components/orders/orders/orders.component.css
  src/app/components/orders/orders/orders.component.html
  src/app/components/orders/orders/orders.component.spec.ts
  src/app/components/orders/orders/orders.component.ts
  src/app/components/popup/confirmation-popup/confirmation-popup.component.css
  src/app/components/popup/confirmation-popup/confirmation-popup.component.html
  src/app/components/popup/confirmation-popup/confirmation-popup.component.spec.ts
  src/app/components/popup/confirmation-popup/confirmation-popup.component.ts
  src/app/components/popup/popup/popup.component.css
  src/app/components/popup/popup/popup.component.html
  src/app/components/popup/popup/popup.component.spec.ts
  src/app/components/popup/popup/popup.component.ts
  src/app/components/stock-market/forex-detail/forex-detail.component.html
  src/app/components/stock-market/forex-detail/forex-detail.component.ts
  src/app/components/stock-market/forex/forex.component.ts
  src/app/components/stock-market/stock-detail/stock-detail.component.ts
  src/app/components/stock-market/stock-main/stock-main.component.html
  src/app/components/stock-market/stocks/stocks.component.ts
  src/app/components/trades/trades-forex/trades-forex.component.css
  src/app/components/trades/trades-forex/trades-forex.component.html
  src/app/components/trades/trades-forex/trades-forex.component.ts
  src/app/components/trades/trades-main/trades-main.component.css
  src/app/components/trades/trades-main/trades-main.component.html
  src/app/components/trades/trades-main/trades-main.component.ts
  src/app/components/trades/trades/trades.component.css
  src/app/components/trades/trades/trades.component.html
  src/app/components/trades/trades/trades.component.ts
  src/app/components/users/activate-password/activate-password.component.ts
  src/app/components/users/add-user/add-user.component.ts
  src/app/components/users/list-users/list-users.component.ts
  src/app/components/users/login/login.component.ts
  src/app/components/users/my-profile/my-profile.component.ts
  src/app/components/users/reset-password-request/reset-password-request.component.ts
  src/app/components/users/reset-password/reset-password.component.ts
  src/app/components/users/update-user/update-user.component.ts
  src/app/model/orders/listing-type-enum.ts
  src/app/model/orders/make-order-request.ts
  src/app/model/orders/order-action-enum.ts
  src/app/model/orders/order-type-enum.ts
  src/app/model/stocks-enum.ts
  src/app/services/orders/orders.service.spec.ts
  src/app/services/orders/orders.service.ts
  src/app/services/stocks/forex.service.ts
  src/app/services/stocks/stocks.service.ts
  src/app/services/user/current-user.service.ts
  src/environments/environment.ts
  src/styles.css
Labels: size/XL

#65 porudzbine
  src/app/app-routing.module.ts
  src/app/components/app/app.component.css
  src/app/components/app/app.component.html
  src/app/components/app/app.component.ts
  src/app/components/orders/orders/orders.component.css
  src/app/components/orders/orders/orders.component.html
  src/app/components/orders/orders/orders.component.ts
  src/app/model/companies-contract-model.ts
  src/app/model/orders/order-status-enum.ts
  src/app/model/user/user-role-enum.ts
  src/app/services/orders/orders.service.ts
Labels: size/L

#67 Završena orders-admin stranica
  src/app/components/orders/orders-admin/orders-admin.component.css
  src/app/components/orders/orders-admin/orders-admin.component.html
  src/app/components/orders/orders-admin/orders-admin.component.ts
  src/app/components/orders/orders/orders.component.css
  src/app/services/orders/orders.service.ts
Labels: size/L

#71 candlestick chart
  angular.json
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/components/stock-market/stock-detail/stock-detail.component.css
  src/app/components/stock-market/stock-detail/stock-detail.component.html
  src/app/components/stock-market/stock-detail/stock-detail.component.ts
Labels: size/L

#72 chart fix
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/components/stock-market/stock-detail/stock-detail.component.css
  src/app/components/stock-market/stock-detail/stock-detail.component.html
  src/app/components/stock-market/stock-detail/stock-detail.component.ts
Labels: size/L

#74 cypress podesavanja
  cypress/e2e/my-profile.cy.ts
  src/app/components/app/app.component.html
  src/app/guards/login.guard.ts
Labels: size/XS

#81 Odradjeni testovi za trades.cy
  cypress/e2e/trades.cy.ts
  src/app/components/popup/confirmation-popup/confirmation-popup.component.html
  src/app/components/trades/trades-forex/trades-forex.component.html
  src/app/components/trades/trades/trades.component.html
Labels: size/L

#82 listing servis + sitnice
  src/app/app.module.ts
  src/app/components/app/app.component.html
  src/app/components/capital/capital-checking/capital-checking.component.html
  src/app/components/capital/capital-checking/capital-checking.component.ts
  src/app/components/capital/listings-popup/listings-popup.component.css
  src/app/components/capital/listings-popup/listings-popup.component.html
  src/app/components/capital/listings-popup/listings-popup.component.spec.ts
  src/app/components/capital/listings-popup/listings-popup.component.ts
  src/app/services/capital/capital.service.ts
  src/environments/environment.ts
Labels: size/L

#84 "Cypress test za stock-market"
  cypress/e2e/stocks-forex-details.cy.ts
  cypress/support/commands.ts
  src/app/components/app/app.component.html
Labels: size/M

#85 Tests for stocks and forex
  cypress.env.json
  cypress/e2e/stocks-forex.cy.ts
  package-lock.json
  src/app/components/stock-market/forex/forex.component.html
  src/app/components/stock-market/stock-main/stock-main.component.html
  src/app/components/stock-market/stocks/stocks.component.html
Labels: size/M

#83 cypress testovi linkova
  cypress/e2e/navbar.cy.ts
  package-lock.json
  package.json
  src/app/components/app/app.component.html
Labels: size/L

#86 cypress fix, docker, refaktorisanje
  Dockerfile
  angular.json
  cypress/e2e/navbar.cy.ts
  cypress/e2e/stocks-forex-details.cy.ts
  cypress/e2e/stocks-forex.cy.ts
  docker-compose.yml
  package-lock.json
  src/app/components/app/app.component.html
  src/app/components/capital/capital-checking/capital-checking.component.ts
  src/app/components/capital/listings-popup/listings-popup.component.html
  src/app/components/capital/listings-popup/listings-popup.component.ts
  src/app/components/users/login/login.component.ts
  src/environments/environment.prod.ts
Labels: size/L

#91 Popunjena stranica za opcije
  src/app/app.module.ts
  src/app/components/stock-market/options/options.component.css
  src/app/components/stock-market/options/options.component.html
  src/app/components/stock-market/options/options.component.ts
  src/app/model/stocks/option-type-enum.ts
  src/app/model/stocks/stock.ts
  src/app/services/stocks/stocks.service.ts
  src/environments/environment.ts
Labels: size/M

#93 KT3 merge main
  .dockerignore
  Dockerfile
  angular.json
  cypress.env.json
  cypress/e2e/my-profile.cy.ts
  cypress/e2e/navbar.cy.ts
  cypress/e2e/stocks-forex-details.cy.ts
  cypress/e2e/stocks-forex.cy.ts
  cypress/e2e/trades.cy.ts
  cypress/support/commands.ts
  docker-compose.yml
  package-lock.json
  package.json
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/components/app/app.component.html
  src/app/components/capital/capital-checking/capital-checking.component.css
  src/app/components/capital/capital-checking/capital-checking.component.html
  src/app/components/capital/capital-checking/capital-checking.component.ts
  src/app/components/capital/listings-popup/listings-popup.component.css
  src/app/components/capital/listings-popup/listings-popup.component.html
  src/app/components/capital/listings-popup/listings-popup.component.spec.ts
  src/app/components/capital/listings-popup/listings-popup.component.ts
  src/app/components/contracts/add-contract-popup/add-contract-popup.component.html
  src/app/components/home/home.component.css
  src/app/components/home/home.component.html
  src/app/components/home/home.component.ts
  src/app/components/popup/confirmation-popup/confirmation-popup.component.html
  src/app/components/stock-market/forex/forex.component.html
  src/app/components/stock-market/options/options.component.css
  src/app/components/stock-market/options/options.component.html
  src/app/components/stock-market/options/options.component.ts
  src/app/components/stock-market/stock-detail/stock-detail.component.css
  src/app/components/stock-market/stock-detail/stock-detail.component.html
  src/app/components/stock-market/stock-detail/stock-detail.component.ts
  src/app/components/stock-market/stock-main/stock-main.component.html
  src/app/components/stock-market/stocks/stocks.component.html
  src/app/components/trades/trades-forex/trades-forex.component.html
  src/app/components/trades/trades-forex/trades-forex.component.ts
  src/app/components/trades/trades/trades.component.html
  src/app/components/trades/trades/trades.component.ts
  src/app/components/users/login/login.component.html
  src/app/components/users/login/login.component.ts
  src/app/model/capital/bank-account.ts
  src/app/model/capital/listing.ts
  src/app/model/stocks/option-type-enum.ts
  src/app/model/stocks/stock.ts
  src/app/model/user/user-model.ts
  src/app/services/capital/capital.service.spec.ts
  src/app/services/capital/capital.service.ts
  src/app/services/stocks/stocks.service.ts
  src/assets/lottie/stock-animation.json
  src/environments/environment.prod.ts
  src/environments/environment.ts
Labels: size/XXL

#96 finalne izmene
  src/app/components/orders/orders/orders.component.html
Labels: size/XS
