Repository RAF-SI-2022/Banka-1-Frontend, pull requests merged in 2023-07, with the labels that each got.

#138 Add user and account creation html flow
  bank/src/app/app-routing.module.ts
  bank/src/app/app.module.ts
  bank/src/app/components/users/add-account/add-account.component.css
  bank/src/app/components/users/add-account/add-account.component.html
  bank/src/app/components/users/add-account/add-account.component.spec.ts
  bank/src/app/components/users/add-account/add-account.component.ts
  bank/src/app/components/users/add-user/add-user.component.html
  bank/src/app/components/users/add-user/add-user.component.ts
  bank/src/app/components/users/update-user/update-user.component.css
  bank/src/app/model/bank-account/bank-account-model.ts
  bank/src/app/model/user/user-model.ts
  bank/src/app/services/user/user.service.ts
Labels: size/L, lgtm

#142 Kreiranje racuna
  bank/src/app/components/accounts/create-account/create-account-main/create-account-main.component.html
  bank/src/app/components/accounts/create-account/create-account-main/create-account-main.component.ts
  bank/src/app/components/accounts/create-account/create-bussiness-account/create-bussiness-account.component.html
  bank/src/app/components/accounts/create-account/create-bussiness-account/create-bussiness-account.component.ts
  bank/src/app/components/accounts/create-account/create-current-account/create-current-account.component.html
  bank/src/app/components/accounts/create-account/create-current-account/create-current-account.component.ts
  bank/src/app/components/accounts/create-account/create-foreign-currency-account/create-foreign-currency-account.component.html
  bank/src/app/components/accounts/create-account/create-foreign-currency-account/create-foreign-currency-account.component.ts
  bank/src/app/components/natural-persons/natural-persons.component.ts
  bank/src/app/services/account/account.service.ts
Labels: lgtm

#148 CD test
  .prow/postsubmits.yaml
  README.md
  bank/README.md
  bank/angular.json
  bank/cypress.env.json
  bank/cypress/e2e/accounts.cy.ts
  bank/cypress/e2e/navbar.cy.ts
  bank/cypress/e2e/transfer.cy.ts
  bank/cypress/support/commands.ts
  bank/src/app/app-routing.module.ts
  bank/src/app/components/accounts/accounts/account-details/account-detail/account-detail.component.ts
  bank/src/app/components/accounts/create-account/create-account-main/create-account-main.component.html
  bank/src/app/components/accounts/create-account/create-current-account/create-current-account.component.html
  bank/src/app/components/accounts/create-account/create-foreign-currency-account/create-foreign-currency-account.component.html
  bank/src/app/components/app/app.component.html
  bank/src/app/components/home/home.component.html
  bank/src/app/components/payments/popup/transfer-approval-popup/transfer-approval-popup.component.html
  bank/src/app/components/payments/popup/transfer-approval-popup/transfer-approval-popup.component.ts
  bank/src/app/components/payments/transfer/transfer.component.html
  kubernetes/bank-front.yaml
  kubernetes/ingress.yaml
  kubernetes/stock-market-front.yaml
  stock-market/README.md
Labels: size/XL

#149 Drugi pokušaj CD testa
  kubernetes/ingress.yaml
Labels: size/XS

#150 Treći pokušaj CD testa
  .prow/postsubmits.yaml
  kubernetes/ingress.yaml
Labels: size/S

#151 Četvrti CD test
  kubernetes/bank-front.yaml
Labels: size/XS

#161 Izmene nginx servera i ruta, preimenovan jwt parametar
  bank/cypress/e2e/login.cy.ts
  bank/nginx.conf
  bank/src/app/app-routing.module.ts
  bank/src/app/app.module.ts
  bank/src/app/components/accounts/accounts/accounts.component.html
  bank/src/app/components/accounts/accounts/accounts.component.ts
  bank/src/app/components/app/app.component.html
  bank/src/app/components/exchange/exchange-confirmation-popup/exchange-confirmation-popup.component.css
  bank/src/app/components/exchange/exchange-confirmation-popup/exchange-confirmation-popup.component.html
  bank/src/app/components/exchange/exchange-confirmation-popup/exchange-confirmation-popup.component.spec.ts
  bank/src/app/components/exchange/exchange-confirmation-popup/exchange-confirmation-popup.component.ts
  bank/src/app/components/exchange/exchange-rate/exchange-rate.component.css
  bank/src/app/components/exchange/exchange-rate/exchange-rate.component.html
  bank/src/app/components/exchange/exchange-rate/exchange-rate.component.spec.ts
  bank/src/app/components/exchange/exchange-rate/exchange-rate.component.ts
  bank/src/app/components/exchange/make-exchange/make-exchange.component.css
  bank/src/app/components/exchange/make-exchange/make-exchange.component.html
  bank/src/app/components/exchange/make-exchange/make-exchange.component.spec.ts
  bank/src/app/components/exchange/make-exchange/make-exchange.component.ts
  bank/src/app/components/home-page/home-page.component.html
  bank/src/app/components/payments/new-payment/new-payment.component.html
  bank/src/app/components/payments/new-payment/new-payment.component.ts
  bank/src/app/components/payments/transfer/transfer.component.ts
  bank/src/app/model/account/accounts-model.ts
  bank/src/app/model/exchange/exchange.ts
  bank/src/app/services/account/account.service.ts
  bank/src/app/services/company/company.service.ts
  bank/src/app/services/currency/currency.service.ts
  bank/src/app/services/exchange/exchange.service.spec.ts
  bank/src/app/services/exchange/exchange.service.ts
  bank/src/app/services/payment/payment.service.ts
  bank/src/app/services/user/current-user.service.ts
  bank/src/app/services/user/user.service.ts
  bank/src/environments/environment.prod.ts
  stock-market/cypress/e2e/login.cy.ts
  stock-market/src/app/services/account/account.service.ts
  stock-market/src/app/services/capital/capital.service.ts
  stock-market/src/app/services/companies/companies.service.ts
  stock-market/src/app/services/contacts/contacts.service.ts
  stock-market/src/app/services/contracts/contracts.service.ts
  stock-market/src/app/services/employee/employees.service.ts
  stock-market/src/app/services/options/options.service.ts
  stock-market/src/app/services/orders/orders.service.ts
  stock-market/src/app/services/stocks/forex.service.ts
  stock-market/src/app/services/stocks/stocks.service.ts
  stock-market/src/app/services/user/current-user.service.ts
  stock-market/src/app/services/user/user.service.ts
  stock-market/src/environments/environment.prod.ts
Labels: size/XL

#163 Dodat CD
  .prow/postsubmits.yaml
  bank/Dockerfile
  bank/angular.json
  bank/cypress/e2e/login.cy.ts
  bank/nginx.conf
  bank/src/app/app.module.ts
  bank/src/app/services/account/account.service.ts
  bank/src/app/services/company/company.service.ts
  bank/src/app/services/currency/currency.service.ts
  bank/src/app/services/exchange/exchange.service.ts
  bank/src/app/services/payment/payment.service.ts
  bank/src/app/services/user/current-user.service.ts
  bank/src/app/services/user/user.service.ts
  bank/src/environments/environment.prod.ts
  bank/src/index.html
  kubernetes/bank-front.yaml
  kubernetes/ingress.yaml
  kubernetes/stock-market-front.yaml
  stock-market/cypress/e2e/login.cy.ts
  stock-market/src/app/services/account/account.service.ts
  stock-market/src/app/services/capital/capital.service.ts
  stock-market/src/app/services/companies/companies.service.ts
  stock-market/src/app/services/contacts/contacts.service.ts
  stock-market/src/app/services/contracts/contracts.service.ts
  stock-market/src/app/services/employee/employees.service.ts
  stock-market/src/app/services/options/options.service.ts
  stock-market/src/app/services/orders/orders.service.ts
  stock-market/src/app/services/stocks/forex.service.ts
  stock-market/src/app/services/stocks/stocks.service.ts
  stock-market/src/app/services/user/current-user.service.ts
  stock-market/src/app/services/user/user.service.ts
  stock-market/src/environments/environment.prod.ts
Labels: size/L

#164 Izmenjen deployment da bude direktno na production
  .prow/postsubmits.yaml
Labels: size/S

#167 prow test
  bank/src/app/components/users/login/login.component.html
Labels: size/XS
