Repository RAF-SI-2022/Banka-1-Frontend, pull requests merged in 2023-06, with the labels that each got.

#119 CRUD for accounts and contacts
  package-lock.json
  src/app/app.module.ts
  src/app/components/companies/account-details-popup/account-details-popup.component.css
  src/app/components/companies/account-details-popup/account-details-popup.component.html
  src/app/components/companies/account-details-popup/account-details-popup.component.spec.ts
  src/app/components/companies/account-details-popup/account-details-popup.component.ts
  src/app/components/companies/companies/companies.component.html
  src/app/components/companies/companies/companies.component.ts
  src/app/components/companies/company-details/company-details.component.html
  src/app/components/companies/company-details/company-details.component.ts
  src/app/components/companies/contact-details-popup/contact-details-popup.component.css
  src/app/components/companies/contact-details-popup/contact-details-popup.component.html
  src/app/components/companies/contact-details-popup/contact-details-popup.component.spec.ts
  src/app/components/companies/contact-details-popup/contact-details-popup.component.ts
  src/app/components/companies/create-account-popup/create-account-popup.component.css
  src/app/components/companies/create-account-popup/create-account-popup.component.html
  src/app/components/companies/create-account-popup/create-account-popup.component.spec.ts
  src/app/components/companies/create-account-popup/create-account-popup.component.ts
  src/app/components/companies/create-company-popup/create-company-popup.component.html
  src/app/components/companies/create-company-popup/create-company-popup.component.ts
  src/app/components/companies/create-contact-popup/create-contact-popup.component.css
  src/app/components/companies/create-contact-popup/create-contact-popup.component.html
  src/app/components/companies/create-contact-popup/create-contact-popup.component.spec.ts
  src/app/components/companies/create-contact-popup/create-contact-popup.component.ts
  src/app/model/account/account.ts
  src/app/model/companies/company.ts
  src/app/model/contacts/contact-request.ts
  src/app/model/contacts/contacts-response.ts
  src/app/services/account/account.service.spec.ts
  src/app/services/account/account.service.ts
  src/app/services/companies/companies.service.spec.ts
  src/app/services/companies/companies.service.ts
  src/app/services/contacts/contacts.service.spec.ts
  src/app/services/contacts/contacts.service.ts
  src/environments/environment.ts
Labels: size/XXL

#122 Companies
  package-lock.json
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/components/companies/account-details-popup/account-details-popup.component.css
  src/app/components/companies/account-details-popup/account-details-popup.component.html
  src/app/components/companies/account-details-popup/account-details-popup.component.spec.ts
  src/app/components/companies/account-details-popup/account-details-popup.component.ts
  src/app/components/companies/companies/companies.component.html
  src/app/components/companies/companies/companies.component.ts
  src/app/components/companies/company-details/company-details.component.css
  src/app/components/companies/company-details/company-details.component.html
  src/app/components/companies/company-details/company-details.component.ts
  src/app/components/companies/contact-details-popup/contact-details-popup.component.css
  src/app/components/companies/contact-details-popup/contact-details-popup.component.html
  src/app/components/companies/contact-details-popup/contact-details-popup.component.spec.ts
  src/app/components/companies/contact-details-popup/contact-details-popup.component.ts
  src/app/components/companies/create-account-popup/create-account-popup.component.css
  src/app/components/companies/create-account-popup/create-account-popup.component.html
  src/app/components/companies/create-account-popup/create-account-popup.component.spec.ts
  src/app/components/companies/create-account-popup/create-account-popup.component.ts
  src/app/components/companies/create-company-popup/create-company-popup.component.html
  src/app/components/companies/create-company-popup/create-company-popup.component.ts
  src/app/components/companies/create-contact-popup/create-contact-popup.component.css
  src/app/components/companies/create-contact-popup/create-contact-popup.component.html
  src/app/components/companies/create-contact-popup/create-contact-popup.component.spec.ts
  src/app/components/companies/create-contact-popup/create-contact-popup.component.ts
  src/app/model/account/account.ts
  src/app/model/companies/company.ts
  src/app/model/contacts/contact-request.ts
  src/app/model/contacts/contacts-response.ts
  src/app/services/account/account.service.spec.ts
  src/app/services/account/account.service.ts
  src/app/services/companies/companies.service.spec.ts
  src/app/services/companies/companies.service.ts
  src/app/services/contacts/contacts.service.spec.ts
  src/app/services/contacts/contacts.service.ts
  src/environments/environment.ts
Labels: size/XXL

#124 companies fetch
  src/app/components/contracts/add-contract/add-contract.component.html
  src/app/components/contracts/add-contract/add-contract.component.ts
Labels: size/S

#127 Odradjeni cypress testovi za kompanije
  cypress/e2e/companies.cy.ts
  src/app/components/companies/companies/companies.component.html
  src/app/components/companies/company-details/company-details.component.html
  src/app/components/companies/create-account-popup/create-account-popup.component.html
  src/app/components/companies/create-contact-popup/create-contact-popup.component.html
  src/app/services/companies/companies.service.ts
Labels: size/L

#128 Izmenjeni linkovi ka backendu za production
  src/environments/environment.prod.ts
Labels: size/S
